# Generated by Django 3.1.5 on 2021-01-18 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='EMPTY TITLE', max_length=200),
        ),
    ]
