# Generated by Django 3.1.5 on 2021-01-18 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210118_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='download_count',
            field=models.PositiveIntegerField(default=0, max_length=500),
        ),
    ]
