# Generated by Django 3.1.5 on 2021-01-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210118_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
