# Generated by Django 3.1.5 on 2021-01-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ebook',
            fields=[
                ('id', models.IntegerField(default='-1', primary_key=True, serialize=False)),
                ('title', models.CharField(default=None, max_length=200)),
                ('authors', models.TextField(default=None, max_length=500)),
                ('subjects', models.TextField(default=None, max_length=500)),
                ('bookshelves', models.TextField(default=None, max_length=500)),
                ('languages', models.TextField(default=None, max_length=500)),
                ('copyright', models.TextField(default=None, max_length=500)),
                ('content_url', models.URLField(blank=True, default=None, null=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
