# Generated by Django 3.1.5 on 2021-01-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_gutenberg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='cover_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='download_count',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
