# Generated by Django 3.1.5 on 2021-01-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_gutenberg', '0004_auto_20210123_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='release_date',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
