# Generated by Django 3.1.5 on 2021-01-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_gutenberg', '0005_ebook_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='authors',
            field=models.TextField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='content_url',
            field=models.URLField(default=None),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='title',
            field=models.CharField(default='blabla', max_length=200),
            preserve_default=False,
        ),
    ]
