# Generated by Django 3.1.5 on 2021-01-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_gutenberg', '0007_ebook_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='neighbours',
            field=models.TextField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
