# Generated by Django 3.1.5 on 2021-01-28 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_gutenberg', '0008_ebook_neighbours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ebook',
            old_name='neighbours',
            new_name='neighbors',
        ),
    ]
