# Generated by Django 3.1.5 on 2021-01-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_gutenberg', '0009_auto_20210128_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='keywords',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
